# Generated by Django 5.2.4 on 2026-10-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_username_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='kind',
            field=models.CharField(choices=[('deposit', 'شارژ کیف پول'), ('withdraw', 'برداشت به حساب'), ('escrow_hold', 'پرداخت به امانت'), ('escrow_release', 'آزادسازی وجه فروش'), ('refund', 'بازگشت وجه'), ('boost', 'نردبان آگهی'), ('adjust', 'اصلاح توسط پشتیبانی')], max_length=20),
        ),
    ]
