# Generated by Django 5.2.4 on 2026-10-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_wallettransaction_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='kind',
            field=models.CharField(choices=[('deposit', 'شارژ کیف پول'), ('withdraw', 'برداشت به حساب'), ('escrow_hold', 'پرداخت امن'), ('escrow_release', 'واریز پول به فروشنده'), ('refund', 'برگشت پول'), ('boost', 'نردبان آگهی'), ('adjust', 'اصلاح توسط پشتیبانی')], max_length=20),
        ),
    ]
