# Generated by Django 5.2.4 on 2026-10-02 19:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='circle-dot', max_length=30)),
                ('text', models.CharField(max_length=300)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فعالیت کارشناس',
                'verbose_name_plural': 'فعالیت کارشناسان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='کارمزد واسطه\u200cگری (درصد)')),
                ('fee_min', models.PositiveBigIntegerField(verbose_name='حداقل کارمزد (تومان)')),
                ('fee_max', models.PositiveBigIntegerField(verbose_name='سقف کارمزد (تومان)')),
                ('seller_delivery_hours', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)], verbose_name='مهلت تحویل فروشنده (ساعت)')),
                ('inspection_hours', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(720)], verbose_name='مهلت بررسی خریدار (ساعت)')),
                ('listing_auto_approve', models.BooleanField(default=False, verbose_name='انتشار خودکار آگهی\u200cها')),
                ('announcement', models.CharField(blank=True, max_length=200, verbose_name='اطلاعیه بالای سایت')),
                ('announcement_tone', models.CharField(choices=[('info', 'اطلاع\u200cرسانی'), ('warning', 'هشدار'), ('success', 'خبر خوب')], default='info', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
            },
        ),
    ]
