# Generated by Django 5.2.4 on 2026-10-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت شد؛ منتظر تحویل فروشنده'), ('verifying', 'بررسی اکانت توسط واسط'), ('delivered', 'تحویل به خریدار؛ زمان بررسی'), ('completed', 'تکمیل شد'), ('disputed', 'در حال بررسی مشکل'), ('cancelled', 'لغو شد'), ('refunded', 'پول به خریدار برگشت')], db_index=True, default='pending_payment', max_length=20),
        ),
    ]
