# Generated by Django 5.2.4 on 2026-10-02 11:33

import apps.listings.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='نام')),
                ('name_en', models.CharField(max_length=60, verbose_name='نام لاتین')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='gamepad-2', max_length=40, verbose_name='آیکن Lucide')),
                ('tone', models.CharField(default='#C8553D', max_length=7, verbose_name='رنگ کارت')),
                ('tagline', models.CharField(blank=True, max_length=120, verbose_name='توضیح کوتاه')),
                ('platforms', models.JSONField(default=list, verbose_name='پلتفرم\u200cها')),
                ('attribute_schema', models.JSONField(default=list, help_text='لیستی از {"key","label","type":number|select|text|bool,"options":[],"unit":"","icon":""}', verbose_name='فیلدهای اختصاصی')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'بازی',
                'verbose_name_plural': 'بازی\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.listings.models._code, editable=False, max_length=8, unique=True)),
                ('title', models.CharField(max_length=80, verbose_name='عنوان آگهی')),
                ('description', models.TextField(max_length=3000, verbose_name='توضیحات')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت (تومان)')),
                ('negotiable', models.BooleanField(default=False, verbose_name='قیمت توافقی است')),
                ('platform', models.CharField(choices=[('pc', 'PC'), ('playstation', 'پلی\u200cاستیشن'), ('xbox', 'ایکس\u200cباکس'), ('mobile', 'موبایل'), ('switch', 'نینتندو سوییچ'), ('cross', 'کراس\u200cپلتفرم')], max_length=20, verbose_name='پلتفرم')),
                ('region', models.CharField(blank=True, max_length=40, verbose_name='ریجن / سرور')),
                ('level', models.PositiveIntegerField(blank=True, null=True, verbose_name='لول / رنک عددی')),
                ('attrs', models.JSONField(blank=True, default=dict)),
                ('email_access', models.CharField(choices=[('full', 'ایمیل اصلی تحویل داده می\u200cشود'), ('changeable', 'ایمیل قابل تغییر است'), ('none', 'دسترسی ایمیل ندارد')], default='changeable', max_length=12, verbose_name='وضعیت ایمیل')),
                ('first_owner', models.BooleanField(default=False, verbose_name='مالک اول هستم')),
                ('ban_free', models.BooleanField(default=True, verbose_name='سابقه بن ندارد')),
                ('has_2fa', models.BooleanField(default=False, verbose_name='تأیید دومرحله\u200cای قابل انتقال')),
                ('fee_payer', models.CharField(choices=[('buyer', 'خریدار'), ('seller', 'فروشنده'), ('split', 'نصف\u200cنصف')], default='buyer', max_length=8, verbose_name='پرداخت کارمزد')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('active', 'فعال'), ('reserved', 'در حال معامله'), ('sold', 'فروخته شد'), ('rejected', 'رد شده'), ('archived', 'بایگانی')], db_index=True, default='pending', max_length=10)),
                ('reject_reason', models.CharField(blank=True, max_length=200)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bumped_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.game')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی\u200cها',
                'ordering': ['-bumped_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/%Y/%m/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار پاسخ'), ('accepted', 'پذیرفته شد'), ('declined', 'رد شد')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='listings.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fake', 'اطلاعات اکانت جعلی است'), ('stolen', 'اکانت دزدی یا هک\u200cشده است'), ('outside', 'درخواست معامله خارج از گیمانت'), ('price', 'قیمت غیرواقعی'), ('other', 'سایر موارد')], max_length=10)),
                ('text', models.CharField(blank=True, max_length=300)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='listings.listing')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
