# Generated by Django 5.2.4 on 2026-10-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contact_app',
            field=models.CharField(blank=True, choices=[('telegram', 'تلگرام'), ('whatsapp', 'واتس\u200cاپ'), ('instagram', 'اینستاگرام'), ('discord', 'دیسکورد'), ('eitaa', 'ایتا'), ('bale', 'بله'), ('rubika', 'روبیکا')], max_length=10, verbose_name='پیام\u200cرسان'),
        ),
        migrations.AddField(
            model_name='listing',
            name='contact_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='آیدی / شماره'),
        ),
    ]
