# Generated by Django 5.2.4 on 2026-10-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('fake', 'اطلاعات اکانت جعلی است'), ('stolen', 'اکانت دزدی یا هک\u200cشده است'), ('outside', 'درخواست معامله خارج از لوطی'), ('price', 'قیمت غیرواقعی'), ('other', 'سایر موارد')], max_length=10),
        ),
    ]
