# Generated by Django 5.2.4 on 2026-10-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_brand_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تأیید'), ('active', 'فعال'), ('reserved', 'در حال معامله'), ('sold', 'فروخته شد'), ('rejected', 'رد شده'), ('archived', 'بسته\u200cشده')], db_index=True, default='pending', max_length=10),
        ),
    ]
