# Generated by Django 5.2.4 on 2026-10-03 12:22

from django.db import migrations, models


def backfill_multi(apps, schema_editor):
    Listing = apps.get_model("listings", "Listing")
    for l in Listing.objects.all().only("id", "platform", "platforms", "contact_app", "contact_id", "contacts"):
        changed = False
        if not l.platforms and getattr(l, "platform", ""):
            l.platforms = [l.platform]
            changed = True
        if not l.contacts and getattr(l, "contact_app", "") and getattr(l, "contact_id", ""):
            l.contacts = [{"app": l.contact_app, "id": l.contact_id}]
            changed = True
        if changed:
            Listing.objects.filter(pk=l.pk).update(platforms=l.platforms, contacts=l.contacts)


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contacts',
            field=models.JSONField(blank=True, default=list, verbose_name='راه\u200cهای ارتباطی'),
        ),
        migrations.AddField(
            model_name='listing',
            name='platforms',
            field=models.JSONField(blank=True, default=list, verbose_name='پلتفرم\u200cها (آگهی)'),
        ),
        migrations.RunPython(backfill_multi, migrations.RunPython.noop),
    ]
