# Generated by Django 5.2.4 on 2026-10-02 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('order', 'معامله'), ('chat', 'پیام'), ('listing', 'آگهی'), ('wallet', 'کیف پول'), ('search', 'جستجوی ذخیره\u200cشده'), ('system', 'گیمانت')], default='system', max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(blank=True, max_length=300)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
