# Generated by Django 5.2.4 on 2026-10-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order', 'معامله'), ('chat', 'پیام'), ('listing', 'آگهی'), ('wallet', 'کیف پول'), ('search', 'جستجوی ذخیره\u200cشده'), ('system', 'لوطی')], default='system', max_length=10),
        ),
    ]
